export const WEDDING_DATA = {
  husband: {
    name: "Nguyễn Ngọc Anh",
    bankName: "Ngân hàng A",
    accountOwner: "Nguyễn Ngọc Anh",
    accountNumber: "123456789",
  },
  wife: {
    name: "Nguyễn Mai Phương",
    bankName: "Ngân hàng B",
    accountOwner: "Nguyễn Mai Phương",
    accountNumber: "987654321",
  },
  events: [
    {
      // icon: eventIcon1,
      name: "Ăn Hỏi",
      time: "10:00 AM",
      day: "20",
      month: "7",
      year: "2024",
      address: "45 Nguyễn Khoái, Hai Bà Trưng, Hà Nội",
      mapUrl: "https://maps.google.com/?q=45+Nguyễn+Khoái,+Hai+Bà+Trưng,+Hà+Nội",
      calendarUrl: "#",
    },
    {
      // icon: eventIcon2,
      name: "Đón Dâu",
      time: "10:00 AM",
      day: "20",
      month: "7",
      year: "2024",
      address: "45 Nguyễn Khoái, Hai Bà Trưng, Hà Nội",
      mapUrl: "https://maps.google.com/?q=45+Nguyễn+Khoái,+Hai+Bà+Trưng,+Hà+Nội",
      calendarUrl: "#",
    },
    {
      // icon: eventIcon3,
      name: "Tiệc Cưới",
      time: "10:00 AM",
      day: "20",
      month: "7",
      year: "2024",
      address: "45 Nguyễn Khoái, Hai Bà Trưng, Hà Nội",
      mapUrl: "https://maps.google.com/?q=45+Nguyễn+Khoái,+Hai+Bà+Trưng,+Hà+Nội",
      calendarUrl: "#",
    },
  ],
};
